{
  List<Integer> expected1List=Arrays.asList(5,3,2,0);
  Observable<Integer> expected1=Observable.from(expected1List);
  List<Integer> expected2List=Arrays.asList(10,7,6,4);
  Observable<Integer> expected2=Observable.from(expected2List);
  List<Integer> expected3List=Arrays.asList(9,8,1);
  Observable<Integer> expected3=Observable.from(expected3List);
  Observable<Integer> ordered=OrderedMerge.orderedMerge(new ReverseIntegerComparator(),10,expected1,expected2,expected3);
  final CountDownLatch latch=new CountDownLatch(1);
  final List<Integer> results=new ArrayList();
  ordered.subscribe(new Subscriber<Integer>(){
    @Override public void onCompleted(){
      latch.countDown();
    }
    @Override public void onError(    final Throwable e){
      logger.error("Test failed due to exception",e);
      fail("An error was thrown ");
    }
    @Override public void onNext(    final Integer integer){
      logger.info("onNext invoked with {}",integer);
      results.add(integer);
    }
  }
);
  latch.await();
  List<Integer> expected=Arrays.asList(10,9,8,7,6,5,4,3,2,1,0);
  assertEquals(expected.size(),results.size());
  for (int i=0; i < expected.size(); i++) {
    assertEquals("Same element expected",expected.get(i),results.get(i));
  }
}
